name: Release Flutter App

on:
  workflow_run:
    workflows: ["Build Flutter App"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: ./release-apk

      - name: Download App Bundle
        uses: actions/download-artifact@v4
        with:
          name: release-bundle
          path: ./release-bundle

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release-apk/app-release.apk
            ./release-bundle/app-release.aab
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
